// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { User, UserData } from "./tables/User.sol";
import { Item, ItemData } from "./tables/Item.sol";
